apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: my-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-voting-app
      tier: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: my-voting-app
        tier: postgres
    spec:
      containers:
        - image: postgres
          name: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name:  POSTGRES_PASSWORD
              value: "postgres"


