apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    app: my-voting-app
    tier: results-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-voting-app
    tier: results