apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deployment
  labels:
    app: my-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-voting-app
      tier: results
  template:
    metadata:
      name: results-app
      labels:
        app: my-voting-app
        tier: results
    spec:
      containers:
        - image: dockersamples/examplevotingapp_result
          name: results-app
          ports:
            - containerPort: 80



