apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: my-votinga-app
    tier: voting-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: my-voting-app
    tier: voting